from . import ir_config_parameter
from . import etsy_shop
from . import etsy_shop_source_change_log
from . import etsy_shop_gdrive
from . import etsy_email_log
from . import etsy_sync_health
from . import etsy_api_log
from . import sale_order
from . import sale_order_line
from . import sale_order_fulfillment
from . import etsy_address_change_request
from . import product_product
from . import res_partner
from . import res_config_settings
from . import etsy_message_dedupe
from . import multichannel_enquiry_etsy
from . import etsy_listing
from . import etsy_listing_product
from . import product_attribute
from . import etsy_taxonomy_node
from . import multichannel_listing
