from . import test_email_parser
from . import test_order_creation
from . import test_deduplication
from . import test_image_downloader
from . import test_import_wizard
from . import test_import_wizard_headers
from . import test_multi_currency_parsing
from . import test_product_categorizer
from . import test_us3_product_creation
from . import test_us4_partner_dedup_geo
from . import test_data_migration_wizard
from . import test_data_migration_fix_bodies
from . import test_data_migration_resume
from . import test_data_migration_idempotent
from . import test_data_migration_merges
from . import test_etsy_oauth_pkce
from . import test_etsy_shop_oauth_fields
from . import test_etsy_oauth_flow
from . import test_etsy_api_client
from . import test_etsy_order_payload
from . import test_etsy_channel_adapter
from . import test_etsy_order_ingestor
from . import test_etsy_api_adapter
from . import test_phase1_db_p0_16c
from . import test_etsy_order_syncer
from . import test_etsy_order_ingestor_status_only
from . import test_phase1_db_p0_17
from . import test_etsy_api_log
from . import test_etsy_audit_retrofit
from . import test_address_change_db
from . import test_address_change_workflow
from . import test_etsy_ship_notified_at
from . import test_phase1_db_message_dedupe
from . import test_phase2_orm_message_dedupe
from . import test_image_cron_wired
from . import test_p0_22_db
from . import test_p0_22_orm
from . import test_p0_22_parity
from . import test_p1_10_db
from . import test_p1_10_orm
from . import test_phase2_order_creator_design_seed
from . import test_p1_12_db
from . import test_p1_12_orm
from . import test_p1_11a_phase1_db
from . import test_p1_11a_phase2_orm
from . import test_p1_11_runbook_phase1_db
from . import test_p1_11_runbook_phase2_orm
from . import test_p_list_pull_phase1_db
from . import test_p_list_pull_phase2_orm
from . import test_p_list_inv_pull_phase1_db
from . import test_p_list_inv_pull_phase2_orm
from . import test_phase1_hub_backfill_db
from . import test_phase2_hub_backfill_orm
from . import test_phase1_p0_13_indexes_db
from . import test_phase1_pub_client_db
from . import test_phase2_pub_client_orm
from . import test_phase2_pub_draft_orm
from . import test_phase2_pub_inventory_orm
from . import test_phase2_pub_images_orm
from . import test_phase2_pub_publish_orm
from . import test_phase2_sku_drift_etsy_orm
from . import test_phase2_pub_publish_button_orm
from . import test_phase2_buyer_message_orm
from . import test_phase2_enquiry_alias_orm
from . import test_phase2_pub_tags_payload_orm
from . import test_phase2_pub_personalization_payload_orm
from . import test_phase2_pub_personalization_endpoints_orm
from . import test_phase2_pub_per_product_defaults_payload_orm
from . import test_phase2_pub_materials_payload_orm
from . import test_phase1_pub_variant_properties_db
from . import test_phase2_pub_variant_properties_orm
from . import test_phase1_pub_weight_dimensions_db
from . import test_phase2_pub_weight_dimensions_orm
from . import test_p1_11_shopid_bootstrap_phase1_db
from . import test_p1_11_shopid_bootstrap_phase2_orm
from . import test_p_uat_fix_api_log_http_status
from . import test_p_bug_esty_188_phase1_db
from . import test_p_bug_esty_188_phase2_orm
from . import test_p_bug_esty_188_phase1_db_iter2
from . import test_p_bug_esty_188_phase2_orm_iter2
from . import test_p_bug_esty_188_phase2_orm_iter3
from . import test_p_list_video_orm
from . import test_p_list_category_orm
from . import test_p_list_shipping_orm
from . import test_p_list_how_its_made_orm
from . import test_p_list_attributes_orm
from . import test_p_list_attr_config_orm
from . import test_p_enh_esty_195_phase1_db
from . import test_p_enh_esty_195_phase2_orm
from . import test_p_enh_esty_190_phase1_db
from . import test_p_enh_esty_190_phase2_orm
from . import test_etsy_shop_form_curation
from . import test_p_list_publish_from_listing_phase1_db
from . import test_p_list_publish_from_listing_phase2_orm
from . import test_p_pub_resolver_casing_bug
from . import test_p_list_publish_state_sync_phase2_orm
from . import test_p_list_image_wire_hero_phase2_orm
from . import test_p_list_video_draft_parity_orm
from . import test_p_list_ship_create_db
from . import test_p_list_ship_create_orm
